-- =====================================================================
-- 鈺見自然便當店 - Supabase 資料庫初始化腳本
-- 使用方式：整份複製貼到 Supabase Dashboard → SQL Editor → Run
-- 本腳本可重複執行（不會重複建表、重複寫入預設商品或重複加入 Realtime）
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. 商品資料表 products
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.products (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT        NOT NULL,
  category      TEXT        DEFAULT '招牌便當',
  diet_type     TEXT        DEFAULT '全素'
                CHECK (diet_type IN ('全素', '蛋素', '奶素', '蛋奶素')),
  price         INTEGER     NOT NULL CHECK (price >= 0),
  stock         INTEGER     NOT NULL DEFAULT 30 CHECK (stock >= 0),
  is_available  BOOLEAN     NOT NULL DEFAULT true,
  pos_code      TEXT,                                   -- 預留給傳統 POS 串接用
  created_at    TIMESTAMPTZ DEFAULT NOW()
);


-- ---------------------------------------------------------------------
-- 2. 訂單資料表 orders
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.orders (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no         TEXT        NOT NULL,                -- 當日流水號，如 #001
  customer_name    TEXT        NOT NULL,
  customer_phone   TEXT        NOT NULL,
  order_type       TEXT        DEFAULT '外帶自取',
  pickup_time      TEXT        DEFAULT '立即製作',
  items_json       JSONB       NOT NULL,
  total_amount     INTEGER     NOT NULL CHECK (total_amount >= 0),
  status           TEXT        NOT NULL DEFAULT 'PENDING'
                   CHECK (status IN ('PENDING', 'PREPARING', 'COMPLETED', 'CANCELLED')),
  is_paid          BOOLEAN     NOT NULL DEFAULT false,
  pos_sync_status  BOOLEAN     NOT NULL DEFAULT false,  -- 預留 POS 同步標記
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 訂單佇列一律依訂餐時間由早到晚排序（created_at ASC）
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders (created_at ASC);


-- ---------------------------------------------------------------------
-- 3. 預設商品（僅在 products 為空時寫入，避免重複執行時重複新增）
-- ---------------------------------------------------------------------
INSERT INTO public.products (name, category, diet_type, price, stock, pos_code)
SELECT v.name, v.category, v.diet_type, v.price, v.stock, v.pos_code
FROM (VALUES
  ('素G排便當',                     '招牌便當', '全素',  100, 25, 'B01'),
  ('薯餅便當',                       '招牌便當', '全素',  100, 20, 'B02'),
  ('蔬菜排便當',                     '招牌便當', '全素',  100, 20, 'B03'),
  ('素D排便當',                      '招牌便當', '全素',  100, 25, 'B04'),
  ('白帶魚便當',                     '招牌便當', '全素',  100, 15, 'B05'),
  ('素鱈魚便當',                     '招牌便當', '全素',  100, 15, 'B06'),
  ('吉祥團圓素食年菜組 (六菜一湯)',  '年菜預購', '全素', 2880, 10, 'NY01')
) AS v(name, category, diet_type, price, stock, pos_code)
WHERE NOT EXISTS (SELECT 1 FROM public.products);


-- ---------------------------------------------------------------------
-- 4. 下單 RPC：create_bento_order
--
-- 前端呼叫方式：
--   supabase.rpc('create_bento_order', {
--     p_customer_name:  '王小明',
--     p_customer_phone: '0912345678',
--     p_order_type:     '外帶自取',
--     p_pickup_time:    '立即製作',
--     p_items: [
--       { "product_id": 1, "qty": 2, "options": ["飯少", "要加辣"] },
--       { "product_id": 1, "qty": 1, "options": [] },
--       { "product_id": 3, "qty": 1 }
--     ]
--   })
--
-- 回傳：{ "order_id": 12, "order_no": "#005", "total_amount": 400 }
--
-- 安全設計：
--   * 前端只傳「商品編號 + 數量 + 客製化備註」，價格一律由資料庫讀取計算，不信任前端金額。
--   * 以 FOR UPDATE 鎖定商品列，同時搶購時排隊處理，防止超賣。
--   * 同一商品不同客製化會分成多行，但庫存檢查以「同商品總數量」計算。
--   * 依商品編號順序上鎖，避免兩筆訂單互相等待造成死結。
--   * 以 advisory lock 確保同一天的流水號不會重複。
--   * 「今日」以台灣時間（Asia/Taipei）計算，跨午夜流水號從 #001 重新開始。
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.create_bento_order(
  p_customer_name  TEXT,
  p_customer_phone TEXT,
  p_order_type     TEXT,
  p_pickup_time    TEXT,
  p_items          JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_name      TEXT := btrim(COALESCE(p_customer_name, ''));
  v_phone     TEXT := btrim(COALESCE(p_customer_phone, ''));
  v_item      RECORD;
  v_line      RECORD;
  v_product   public.products%ROWTYPE;
  v_catalog   JSONB   := '{}'::jsonb;   -- 已鎖定商品的品名與單價快照
  v_info      JSONB;
  v_price     INTEGER;
  v_items_out JSONB   := '[]'::jsonb;
  v_total     INTEGER := 0;
  v_today     DATE    := (NOW() AT TIME ZONE 'Asia/Taipei')::date;
  v_seq       INTEGER;
  v_order_no  TEXT;
  v_order_id  BIGINT;
BEGIN
  -- 4-1. 基本資料檢查
  IF v_name = '' THEN
    RAISE EXCEPTION '請填寫訂購人稱呼';
  END IF;
  IF char_length(v_name) > 50 THEN
    RAISE EXCEPTION '訂購人稱呼過長（最多 50 字）';
  END IF;
  IF v_phone = '' THEN
    RAISE EXCEPTION '請填寫聯絡電話';
  END IF;
  IF char_length(v_phone) > 20 THEN
    RAISE EXCEPTION '聯絡電話格式錯誤';
  END IF;
  IF char_length(COALESCE(p_order_type, '')) > 20 OR char_length(COALESCE(p_pickup_time, '')) > 50 THEN
    RAISE EXCEPTION '取餐資訊格式錯誤';
  END IF;

  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION '購物車是空的，請先選擇餐點';
  END IF;
  IF jsonb_array_length(p_items) > 50 THEN
    RAISE EXCEPTION '單筆訂單品項過多，請分開下單';
  END IF;

  -- 4-2. 品項格式檢查：
  --      product_id 為正整數、qty 為 1~99 的整數、
  --      options（可省略）為最多 10 個、每個最多 20 字的文字陣列
  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_items) AS e
    WHERE CASE
            WHEN jsonb_typeof(e) = 'object'
             AND jsonb_typeof(e -> 'product_id') = 'number'
             AND jsonb_typeof(e -> 'qty') = 'number'
            THEN (e ->> 'product_id')::numeric <> trunc((e ->> 'product_id')::numeric)
              OR (e ->> 'product_id')::numeric NOT BETWEEN 1 AND 9223372036854775807
              OR (e ->> 'qty')::numeric <> trunc((e ->> 'qty')::numeric)
              OR (e ->> 'qty')::numeric NOT BETWEEN 1 AND 99
              OR CASE
                   WHEN e -> 'options' IS NULL OR jsonb_typeof(e -> 'options') = 'null' THEN false
                   WHEN jsonb_typeof(e -> 'options') = 'array' THEN
                        jsonb_array_length(e -> 'options') > 10
                     OR EXISTS (
                          SELECT 1 FROM jsonb_array_elements(e -> 'options') AS o
                          WHERE jsonb_typeof(o) <> 'string' OR char_length(o #>> '{}') > 20
                        )
                   ELSE true
                 END
            ELSE true
          END
  ) THEN
    RAISE EXCEPTION '訂單品項格式錯誤，請重新整理頁面後再試';
  END IF;

  -- 4-3. 依商品合併數量 → 依編號順序鎖定 → 檢查庫存 → 扣庫存
  FOR v_item IN
    SELECT (e ->> 'product_id')::numeric::bigint AS product_id,
           SUM((e ->> 'qty')::numeric)::integer   AS qty
    FROM jsonb_array_elements(p_items) AS e
    GROUP BY 1
    ORDER BY 1
  LOOP
    SELECT * INTO v_product
    FROM public.products
    WHERE id = v_item.product_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION '找不到商品（編號 %），請重新整理菜單', v_item.product_id;
    END IF;

    IF v_product.is_available IS NOT TRUE THEN
      RAISE EXCEPTION '「%」目前已停售', v_product.name;
    END IF;

    IF v_product.stock < v_item.qty THEN
      IF v_product.stock = 0 THEN
        RAISE EXCEPTION '「%」已售完', v_product.name;
      END IF;
      RAISE EXCEPTION '「%」庫存不足，目前僅剩 % 份', v_product.name, v_product.stock;
    END IF;

    -- 扣庫存；扣到 0 自動停售（SET 內兩個運算式都讀取扣除前的 stock）
    UPDATE public.products
    SET stock        = stock - v_item.qty,
        is_available = (stock - v_item.qty) > 0
    WHERE id = v_product.id;

    v_catalog := v_catalog || jsonb_build_object(
      v_product.id::text,
      jsonb_build_object('name', v_product.name, 'diet_type', v_product.diet_type, 'price', v_product.price)
    );
  END LOOP;

  -- 4-4. 依顧客原本的品項順序產生明細與金額
  --      明細存下當下的品名與單價快照，日後改價不影響歷史訂單
  FOR v_line IN
    SELECT (e ->> 'product_id')::numeric::bigint AS product_id,
           (e ->> 'qty')::numeric::integer        AS qty,
           COALESCE(NULLIF(e -> 'options', 'null'::jsonb), '[]'::jsonb) AS options
    FROM jsonb_array_elements(p_items) WITH ORDINALITY AS t(e, ord)
    ORDER BY ord
  LOOP
    v_info  := v_catalog -> v_line.product_id::text;
    v_price := (v_info ->> 'price')::integer;
    v_total := v_total + v_price * v_line.qty;

    v_items_out := v_items_out || jsonb_build_array(jsonb_build_object(
      'product_id', v_line.product_id,
      'name',       v_info ->> 'name',
      'diet_type',  v_info ->> 'diet_type',
      'price',      v_price,
      'qty',        v_line.qty,
      'subtotal',   v_price * v_line.qty,
      'options',    v_line.options
    ));
  END LOOP;

  -- 4-5. 產生今日流水號（advisory lock 讓同一天的編號依序發放、不重複）
  PERFORM pg_advisory_xact_lock(hashtext('bento_order_no'), to_char(v_today, 'YYYYMMDD')::integer);

  SELECT COUNT(*) + 1 INTO v_seq
  FROM public.orders
  WHERE created_at >= (v_today::timestamp       AT TIME ZONE 'Asia/Taipei')
    AND created_at <  ((v_today + 1)::timestamp AT TIME ZONE 'Asia/Taipei');

  v_order_no := '#' || CASE WHEN v_seq < 1000 THEN lpad(v_seq::text, 3, '0') ELSE v_seq::text END;

  -- 4-6. 寫入訂單
  INSERT INTO public.orders (
    order_no, customer_name, customer_phone, order_type, pickup_time, items_json, total_amount
  ) VALUES (
    v_order_no,
    v_name,
    v_phone,
    COALESCE(NULLIF(btrim(p_order_type), ''),  '外帶自取'),
    COALESCE(NULLIF(btrim(p_pickup_time), ''), '立即製作'),
    v_items_out,
    v_total
  )
  RETURNING id INTO v_order_id;

  RETURN jsonb_build_object(
    'order_id',     v_order_id,
    'order_no',     v_order_no,
    'total_amount', v_total
  );
END;
$$;


-- ---------------------------------------------------------------------
-- 4-B. 取消訂單 RPC：cancel_bento_order
--      將訂單改為 CANCELLED，並把便當份數加回庫存（原本售完的會自動恢復供應）
--      前端呼叫：supabase.rpc('cancel_bento_order', { p_order_id: 12 })
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.cancel_bento_order(p_order_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.orders%ROWTYPE;
  v_item  RECORD;
BEGIN
  SELECT * INTO v_order FROM public.orders WHERE id = p_order_id FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION '找不到這筆訂單';
  END IF;
  IF v_order.status NOT IN ('PENDING', 'PREPARING') THEN
    RAISE EXCEPTION '訂單 % 已完成或已取消，無法再取消', v_order.order_no;
  END IF;

  FOR v_item IN
    SELECT (e ->> 'product_id')::numeric::bigint AS product_id,
           SUM((e ->> 'qty')::numeric)::integer   AS qty
    FROM jsonb_array_elements(v_order.items_json) AS e
    GROUP BY 1
    ORDER BY 1
  LOOP
    UPDATE public.products
    SET stock        = stock + v_item.qty,
        is_available = CASE WHEN stock = 0 THEN true ELSE is_available END
    WHERE id = v_item.product_id;   -- 商品已被刪除時不會更新任何資料，直接略過
  END LOOP;

  UPDATE public.orders SET status = 'CANCELLED' WHERE id = p_order_id;

  RETURN jsonb_build_object('order_id', p_order_id, 'order_no', v_order.order_no, 'status', 'CANCELLED');
END;
$$;


-- ---------------------------------------------------------------------
-- 4-C. 快速調整庫存 RPC：adjust_product_stock
--      以「加減量」原子更新庫存，避免後台按 +1 時覆蓋掉同時間顧客下單扣掉的數量
--      庫存歸 0 自動停售；從 0 補貨自動恢復供應
--      前端呼叫：supabase.rpc('adjust_product_stock', { p_product_id: 1, p_delta: -5 })
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.adjust_product_stock(p_product_id BIGINT, p_delta INTEGER)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_product public.products%ROWTYPE;
BEGIN
  IF p_delta IS NULL OR p_delta NOT BETWEEN -1000 AND 1000 THEN
    RAISE EXCEPTION '庫存調整數量需介於 -1000 ~ 1000';
  END IF;

  UPDATE public.products
  SET stock        = GREATEST(stock + p_delta, 0),
      is_available = CASE
                       WHEN GREATEST(stock + p_delta, 0) = 0 THEN false
                       WHEN stock = 0                        THEN true
                       ELSE is_available
                     END
  WHERE id = p_product_id
  RETURNING * INTO v_product;

  IF NOT FOUND THEN
    RAISE EXCEPTION '找不到商品（編號 %）', p_product_id;
  END IF;

  RETURN to_jsonb(v_product);
END;
$$;

-- 只開放 anon / authenticated 呼叫上述函數
REVOKE ALL ON FUNCTION public.create_bento_order(TEXT, TEXT, TEXT, TEXT, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cancel_bento_order(BIGINT)                         FROM PUBLIC;
REVOKE ALL ON FUNCTION public.adjust_product_stock(BIGINT, INTEGER)              FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_bento_order(TEXT, TEXT, TEXT, TEXT, JSONB) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_bento_order(BIGINT)                         TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.adjust_product_stock(BIGINT, INTEGER)              TO anon, authenticated;


-- ---------------------------------------------------------------------
-- 5-1. Realtime 即時推播（已加入過則略過，避免重複執行時報錯）
-- ---------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'products'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
  END IF;
END;
$$;


-- ---------------------------------------------------------------------
-- 5-2. RLS 權限（MVP 階段）
--
-- ⚠ 注意：目前後台只有前端 PIN 碼鎖，沒有真正的帳號登入，
--   所以任何拿到網頁中 anon key 的人，理論上都能直接呼叫 API：
--     - 讀取所有訂單（含顧客姓名、電話）
--     - 修改商品（名稱、價格、庫存）與訂單狀態
--   正式營運前，建議改用 Supabase Auth 讓店家登入，再把下面的
--   寫入權限從 anon 收回、只開放給 authenticated。
--
-- 已先做的防護：
--   * 顧客不能直接 INSERT 訂單，只能透過 create_bento_order 下單（金額由資料庫計算）。
--   * 訂單只開放修改 status / is_paid / pos_sync_status 三個欄位，
--     不能竄改金額、品項或顧客資料。
--   * 訂單不開放刪除（取消請用 cancel_bento_order，保留營收紀錄並歸還庫存）。
-- ---------------------------------------------------------------------
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders   ENABLE ROW LEVEL SECURITY;

-- 欄位層級權限
REVOKE TRUNCATE ON public.products FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.orders FROM anon, authenticated;
GRANT SELECT ON public.orders TO anon, authenticated;
GRANT UPDATE (status, is_paid, pos_sync_status) ON public.orders TO anon, authenticated;

-- products：所有人可讀；後台可新增、修改、刪除商品
DROP POLICY IF EXISTS "products_select_all" ON public.products;
DROP POLICY IF EXISTS "products_insert_mvp" ON public.products;
DROP POLICY IF EXISTS "products_update_mvp" ON public.products;
DROP POLICY IF EXISTS "products_delete_mvp" ON public.products;

CREATE POLICY "products_select_all" ON public.products
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "products_insert_mvp" ON public.products
  FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "products_update_mvp" ON public.products
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "products_delete_mvp" ON public.products
  FOR DELETE TO anon, authenticated USING (true);

-- orders：所有人可讀（後台佇列與 Realtime 推播需要）；只能改狀態欄位
DROP POLICY IF EXISTS "orders_select_all" ON public.orders;
DROP POLICY IF EXISTS "orders_update_status_mvp" ON public.orders;

CREATE POLICY "orders_select_all" ON public.orders
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "orders_update_status_mvp" ON public.orders
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
